# Generated by Django 4.2.16 on 2024-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoup',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
