# Generated by Django 4.2.16 on 2024-10-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_autoup_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoup',
            options={'ordering': ('days',), 'verbose_name': 'Auto Up'},
        ),
    ]
