# Generated by Django 5.1.1 on 2024-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_businessaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=50, verbose_name='Tariff name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('duration_days', models.IntegerField(choices=[(30, '1 month'), (90, '3 months'), (180, '6 months'), (365, '12 months')], verbose_name='Duration in days')),
                ('limit', models.IntegerField(verbose_name='Limit')),
                ('own_branded_page', models.BooleanField(default=False, verbose_name='собственная брендированная страница')),
                ('auto_up', models.BooleanField(default=False, verbose_name='UP')),
                ('placement_on_main_page', models.BooleanField(default=False, verbose_name='размещение на главной странице сайта и в мобильных приложениях')),
                ('tag_with_company_name', models.BooleanField(default=False, verbose_name='метка на объявлениях с названием вашей компании')),
                ('no_ad_photos', models.BooleanField(default=False, verbose_name='отсутствие рекламы среди фотографий объявления')),
                ('without_competitors', models.BooleanField(default=False, verbose_name='отсутствие конкурентов под вашим объявлением')),
                ('auto_business_priority', models.BooleanField(default=False, verbose_name='приоритет в разделе Автобизнес (выше планов Базовый и Продвинутый)')),
                ('crm_sync', models.BooleanField(default=False, verbose_name='автоматическая загрузка объявлений с вашего сайта или CRM')),
                ('search_by_ads', models.BooleanField(default=False, verbose_name='поиск по вашим объявлениям')),
                ('body_condition_status', models.BooleanField(default=False, verbose_name='возможность отметить состояние кузова')),
            ],
            options={
                'verbose_name': 'Tariff Plan',
                'verbose_name_plural': 'Tariff Plans',
                'unique_together': {('name', 'duration_days')},
            },
        ),
    ]
