# Generated by Django 4.2.16 on 2024-10-18 12:04

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_property_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentialcategory',
            options={'ordering': ['id'], 'verbose_name': 'Жилой комплекс', 'verbose_name_plural': 'Жилой комплекс'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='property',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='residentialcategory',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='location',
            name='admin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='active_post',
            field=models.BooleanField(default=True, verbose_name='Активный пост'),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_height',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='property',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='about_complex',
            field=models.TextField(blank=True, null=True, verbose_name='Об объекте'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата сдачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='housing_class',
            field=models.CharField(choices=[('econom', 'эконом'), ('comfort', 'комфорт'), ('business', 'бизнес'), ('premuim', 'премуим')], default=django.utils.timezone.now, max_length=50, verbose_name='Тип класса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='lat',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='location',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='house.location', verbose_name='Расположение обьекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='lon',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='object_state',
            field=models.CharField(choices=[('scheduled', 'запланирован'), ('under construction', 'строится'), ('finalized', 'завершен'), ('commissioned', 'сдан в эксплуатацию'), ('frozen', 'заморожен')], default=django.utils.timezone.now, max_length=50, verbose_name='Состояние обьекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='price',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='storey',
            field=models.IntegerField(default=django.utils.timezone.now, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Этажность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='type_building',
            field=models.CharField(blank=True, choices=[('Brick', 'Кирпичный'), ('Panel', 'Панельный'), ('Monolith', 'Монолитный')], max_length=50, null=True, verbose_name='Тип строения'),
        ),
        migrations.AddField(
            model_name='residentialcategory',
            name='type_heating',
            field=models.CharField(blank=True, choices=[('Central', 'Центральное'), ('Gas', 'На газе'), ('Electric', 'Электрическое'), ('Mixed', 'Смешанное'), ('Solid fuel', 'На твердом топливе'), ('Liquid fuel', 'На жидком топливе'), ('No heating', 'Без отопления'), ('Autonomous', 'Автономное')], max_length=50, null=True, verbose_name='Тип отопления'),
        ),
        migrations.AlterField(
            model_name='location',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='iso2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='population',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
