# Generated by Django 4.2.16 on 2024-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_alter_residentialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcategory',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='residentialcategory',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
