# Generated by Django 4.2.16 on 2024-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_residentialcategory_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lng',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='residentialcategory',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentialcategory',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
