# Generated by Django 4.2.16 on 2024-10-10 15:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CarColors',
            fields=[
                ('id', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, primary_key=True, samples=None, serialize=False, verbose_name='HEX')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Car colors',
                'verbose_name_plural': 'Car colors',
            },
        ),
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_min', models.IntegerField(blank=True, null=True, verbose_name='Price min')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('img', models.ImageField(null=True, upload_to='cars/mark', verbose_name='Image')),
                ('year_begin', models.CharField(max_length=255, null=True, verbose_name='Year begin')),
                ('year_end', models.CharField(max_length=255, null=True, verbose_name='Year end')),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('img', models.ImageField(null=True, upload_to='cars/mark', verbose_name='Image')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Name rus')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_rus', models.CharField(max_length=255, null=True, verbose_name='Name rus')),
                ('id_car_mark', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmark', verbose_name='Id car mark')),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionForFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_generation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_serie', to='cars.cargeneration', verbose_name='Id car generation')),
                ('id_car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Id car model')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.CreateModel(
            name='CarOptionValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_base', models.PositiveSmallIntegerField(verbose_name='Is base')),
                ('id_car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carequipment', verbose_name='Id car equipment')),
                ('id_car_option', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.caroption', verbose_name='Id car option')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.AddField(
            model_name='caroption',
            name='id_car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.AddField(
            model_name='caroption',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.caroption', verbose_name='Id parent'),
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Id car model')),
                ('id_car_serie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carserie', verbose_name='Id car serie')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.AddField(
            model_name='carmodel',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='id_car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmodel', verbose_name='Id car model'),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='id_car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='id_car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmodification', verbose_name='Id car modification'),
        ),
        migrations.AddField(
            model_name='carequipment',
            name='id_car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit')),
                ('id_car_characteristic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='car_characteristic_value', to='cars.carcharacteristic', verbose_name='Id car characteristic')),
                ('id_car_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodification', verbose_name='Car modification')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.AddField(
            model_name='carcharacteristic',
            name='id_car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type'),
        ),
        migrations.AddField(
            model_name='carcharacteristic',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcharacteristic', verbose_name='Id parent'),
        ),
    ]
