# Generated by Django 5.1.1 on 2024-09-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carmark_id_car_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcharacteristic', verbose_name='Id parent')),
            ],
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('year_begin', models.CharField(max_length=255, verbose_name='Year begin')),
                ('year_end', models.CharField(max_length=255, verbose_name='Year end')),
                ('id_car_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmodel', verbose_name='Id car model')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Id car model')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.CreateModel(
            name='CarEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_min', models.IntegerField(verbose_name='Price min')),
                ('year', models.IntegerField(verbose_name='year')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
                ('id_car_modification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmodification', verbose_name='Id car modification')),
            ],
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('unit', models.CharField(max_length=255, verbose_name='Unit')),
                ('id_car_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carcharacteristic', verbose_name='Id car characteristic')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
                ('id_car_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodification', verbose_name='Car modification')),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.caroption', verbose_name='Id parent')),
            ],
        ),
        migrations.CreateModel(
            name='CarOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_base', models.PositiveSmallIntegerField(verbose_name='Is base')),
                ('id_car_equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carequipment', verbose_name='Id car equipment')),
                ('id_car_option', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.caroption', verbose_name='Id car option')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('id_car_generation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cargeneration', verbose_name='Id car generation')),
                ('id_car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Id car model')),
                ('id_car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
        migrations.AddField(
            model_name='carmodification',
            name='id_car_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carserie', verbose_name='Id car serie'),
        ),
    ]
