# Generated by Django 5.1.1 on 2024-09-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_carserie_id_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carserie',
            name='id_car_generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='car_serie', to='cars.cargeneration', verbose_name='Id car generation'),
        ),
        migrations.AlterField(
            model_name='carserie',
            name='id_car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Id car model'),
        ),
    ]
