# Generated by Django 5.1.1 on 2024-09-25 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_alter_carmodel_id_car_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='id_car_characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='car_characteristic_value', to='cars.carcharacteristic', verbose_name='Id car characteristic'),
        ),
    ]
