# Generated by Django 5.1.1 on 2024-09-27 10:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_carcolors'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcolors',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carcolors',
            name='id',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, primary_key=True, samples=None, serialize=False, verbose_name='HEX'),
        ),
    ]
