# Generated by Django 5.1.1 on 2024-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_carcolors_name_alter_carcolors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargeneration',
            name='img',
            field=models.ImageField(null=True, upload_to='cars/mark', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='img',
            field=models.ImageField(null=True, upload_to='cars/mark', verbose_name='Image'),
        ),
    ]
