# Generated by Django 5.1.1 on 2024-10-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_cargeneration_img_carmark_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcolors',
            options={'verbose_name': 'Car colors', 'verbose_name_plural': 'Car colors'},
        ),
    ]
