# Generated by Django 4.2.16 on 2024-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_alter_carcolors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name_rus',
            field=models.CharField(max_length=255, null=True, verbose_name='Name rus'),
        ),
    ]
