# Generated by Django 4.2.16 on 2024-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_alter_carmodel_name_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargeneration',
            name='year_begin',
            field=models.CharField(max_length=255, null=True, verbose_name='Year begin'),
        ),
        migrations.AlterField(
            model_name='cargeneration',
            name='year_end',
            field=models.CharField(max_length=255, null=True, verbose_name='Year end'),
        ),
    ]
