# Generated by Django 5.1.1 on 2024-09-13 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_mark', models.IntegerField(verbose_name='id')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('name_rus', models.CharField(max_length=250, verbose_name='Name rus')),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_type', models.IntegerField(verbose_name='id')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cartype'),
        ),
    ]
