# Generated by Django 5.1.1 on 2024-09-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmark_cartype_delete_car_carmark_id_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cartype', verbose_name='Id car type'),
        ),
    ]
