# Generated by Django 5.1.1 on 2024-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmark_id_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmark',
            name='id_car_mark',
            field=models.IntegerField(verbose_name='iId'),
        ),
        migrations.AlterField(
            model_name='carmark',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='carmark',
            name='name_rus',
            field=models.CharField(max_length=255, verbose_name='Name rus'),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='id_car_type',
            field=models.IntegerField(verbose_name='Id'),
        ),
    ]
