# Generated by Django 5.1.1 on 2024-09-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_cartype_name_alter_carmark_id_car_mark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmark',
            name='id_car_mark',
        ),
        migrations.RemoveField(
            model_name='cartype',
            name='id_car_type',
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_rus', models.CharField(max_length=255, verbose_name='Name rus')),
                ('id_car_mark', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmark', verbose_name='Id car mark')),
                ('id_car_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.cartype', verbose_name='Id car type')),
            ],
        ),
    ]
