# Generated by Django 5.1.1 on 2024-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carcharacteristic_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unit'),
        ),
    ]
