# Generated by Django 5.1.1 on 2024-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carcharacteristicvalue_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carequipment',
            name='price_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price min'),
        ),
    ]
