# Generated by Django 5.1.1 on 2024-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_carequipment_price_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carequipment',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
