# Generated by Django 5.1.1 on 2024-09-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carequipment_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcharacteristicvalue',
            name='id_car_characteristic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cars.carcharacteristic', verbose_name='Id car characteristic'),
        ),
    ]
