# Generated by Django 5.1.1 on 2024-09-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_carserie_id_car_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='id_car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='CarMark', to='cars.carmark', verbose_name='Id car mark'),
        ),
    ]
