# Generated by Django 5.1.1 on 2024-09-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_alter_carmodel_id_car_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='id_car_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cars.carmark', verbose_name='Id car mark'),
        ),
    ]
