# Generated by Django 5.1.1 on 2024-09-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_carcharacteristicvalue_id_car_characteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
