# Generated by Django 4.2.16 on 2024-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsposts',
            name='is_up',
            field=models.BooleanField(default=False, verbose_name='Авто-UP'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='up_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончания Авто-UP'),
        ),
    ]
