# Generated by Django 4.2.16 on 2024-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0002_carsposts_is_up_carsposts_up_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsposts',
            name='is_up',
        ),
        migrations.RemoveField(
            model_name='carsposts',
            name='up_expiration',
        ),
        migrations.AddField(
            model_name='carsposts',
            name='ad_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Ad Color'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='ad_dark_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Ad Dark Color'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='autoup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Auto UP Time'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='autoup_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Auto UP Until'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='colored_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Colored Until'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='featured',
            field=models.BooleanField(blank=True, null=True, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='is_autoup',
            field=models.BooleanField(default=False, verbose_name='Is Auto UP'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is Premium'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Is Top'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Is Urgent'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Is VIP'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='premium_dark_gradient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Premium Dark Gradient'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='premium_gradient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Premium Gradient'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Premium Until'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='topped_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Topped Until'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='urgent_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Urgent Until'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='vipped_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vipped Until'),
        ),
    ]
