# Generated by Django 4.2.16 on 2024-10-10 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars_posts', '0002_alter_carsposts_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsposts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_car', to=settings.AUTH_USER_MODEL, verbose_name='Понравится'),
        ),
    ]
