# Generated by Django 5.1.1 on 2024-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0003_alter_carsposts_options_alter_carsposts_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_kit', models.BooleanField(default=False)),
                ('tinting', models.BooleanField(default=False)),
                ('spoiler', models.BooleanField(default=False)),
                ('alloy_wheel_rims', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('winch', models.BooleanField(default=False)),
                ('roofrack', models.BooleanField(default=False)),
                ('trunk', models.BooleanField(default=False)),
                ('hitch', models.BooleanField(default=False)),
                ('panoramic_roof', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_power_pack', models.BooleanField(default=False)),
                ('anti_theft_alarm', models.BooleanField(default=False)),
                ('remote_car_starter', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('climate_control_system', models.BooleanField(default=False)),
                ('auto_gas_system', models.BooleanField(default=False)),
                ('cruise_control', models.BooleanField(default=False)),
                ('light_sensor', models.BooleanField(default=False)),
                ('heated_steering_wheel', models.BooleanField(default=False)),
                ('seat_ventilation', models.BooleanField(default=False)),
                ('laser_headlights', models.BooleanField(default=False)),
                ('front_seat_heating', models.BooleanField(default=False)),
                ('all_seat_heating', models.BooleanField(default=False)),
                ('mirror_heating_system', models.BooleanField(default=False)),
                ('xenon_headlights', models.BooleanField(default=False)),
                ('bi_xenon_headlights', models.BooleanField(default=False)),
                ('headlight_washer', models.BooleanField(default=False)),
                ('air_suspension', models.BooleanField(default=False)),
                ('seat_memory', models.BooleanField(default=False)),
                ('steering_wheel_memory', models.BooleanField(default=False)),
                ('rain_sensor', models.BooleanField(default=False)),
                ('onboard_computer', models.BooleanField(default=False)),
                ('headlight_adjustment_system', models.BooleanField(default=False)),
                ('keyless_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velour', models.BooleanField(default=False)),
                ('leather', models.BooleanField(default=False)),
                ('window_blinds', models.BooleanField(default=False)),
                ('alcantara', models.BooleanField(default=False)),
                ('combined', models.BooleanField(default=False)),
                ('wood', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.BooleanField(default=False)),
                ('dvd', models.BooleanField(default=False)),
                ('mp3', models.BooleanField(default=False)),
                ('usb', models.BooleanField(default=False)),
                ('subwoofer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.BooleanField(default=False)),
                ('traction_control', models.BooleanField(default=False)),
                ('vehicle_stability_control', models.BooleanField(default=False)),
                ('airbags', models.BooleanField(default=False)),
                ('parking_sensors', models.BooleanField(default=False)),
                ('rear_view_camera', models.BooleanField(default=False)),
            ],
        ),
    ]
