# Generated by Django 4.2.16 on 2024-10-10 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0003_alter_carsposts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
