# Generated by Django 5.1.1 on 2024-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0007_alter_carsposts_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsposts',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
