# Generated by Django 4.2.16 on 2024-10-23 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessaccount',
            options={'ordering': ('-created_at',), 'verbose_name': 'Business Account', 'verbose_name_plural': 'Business Accounts'},
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='business/videos/', verbose_name='Company Video'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
        migrations.CreateModel(
            name='BusinessAccountImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/images/', verbose_name='Image')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.businessaccount')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
