# Generated by Django 4.2.16 on 2024-10-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_businessaccount_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffPlan',
        ),
    ]
