# Generated by Django 4.2.16 on 2024-10-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tariffplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffplan',
            name='auto_business_priority',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='body_condition_status',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='crm_sync',
        ),
    ]
