# Generated by Django 5.1.1 on 2024-09-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_carcolors'),
        ('cars_posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carsposts',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('pre_order', 'Предзаказ'), ('in_transit', 'В пути')], max_length=300, null=True, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.cartype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carcolors', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='condition',
            field=models.CharField(choices=[('good', 'Хорошее'), ('perfect', 'Отличное'), ('salvage', 'Битый'), ('new', 'Новый')], max_length=300, null=True, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='currency',
            field=models.CharField(choices=[('SOM', 'СОМ'), ('USD', 'Доллар')], max_length=300, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='customs_cleared',
            field=models.BooleanField(default=False, verbose_name='Растоможен'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст объявления'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='drive',
            field=models.CharField(choices=[('awd', 'Полный'), ('part_time_awd', 'Полный подключаемый'), ('rwd', 'Задний'), ('fwd', 'Передний')], max_length=300, null=True, verbose_name='Привод'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='engine',
            field=models.CharField(choices=[('gas', 'Газ'), ('petrol', 'Бензиновый'), ('electric', 'Электрический'), ('hybrid', 'Гибридный'), ('diesel', 'Дизельный')], max_length=300, null=True, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='exchange_possibility',
            field=models.CharField(choices=[('will_consider_options', 'Рассмотрю варианты'), ('extra_charge_buyer', 'С доплатой от покупателя'), ('extra_charge_seller', 'С доплатой от продавца'), ('no_additional_payments', 'Обмен без доплат'), ('not_interested', 'Не интересует обмен'), ('real_estate_exchange', 'Обмен на недвижимость'), ('only_exchange', 'Только обмен')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='installment',
            field=models.BooleanField(default=False, verbose_name='Возможно рассрочка'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmark', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='mileage',
            field=models.IntegerField(null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='mileage_unit',
            field=models.CharField(choices=[('km', 'Километры'), ('mi', 'Мили')], max_length=300, null=True, verbose_name='Ед. измерения расстоянии'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodification', verbose_name='Модификация'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='other',
            field=models.CharField(choices=[('recently_delivered', 'Недавно доставлено'), ('tax_paid', 'Налог уплачен'), ('inspection_passed', 'Технический осмотр пройден'), ('no_investment_required', 'Инвестиции не требуются')], max_length=300, null=True, verbose_name='Прочее'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='registration',
            field=models.CharField(choices=[('Kyrgyzstan', 'Кыргызстан'), ('Abkhazia', 'Абхазия'), ('Armenia', 'Армения'), ('Kazakhstan', 'Казахстан'), ('Russia', 'Россия'), ('Belarus', 'Беларусь'), ('Another country', 'Другая страна'), ('Not registered', 'Не зарегистрировано')], max_length=300, null=True, verbose_name='Учёт'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carserie', verbose_name='Кузов'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='steering_wheel',
            field=models.CharField(choices=[('left', 'Левый'), ('right', 'Правый')], max_length=300, null=True, verbose_name='Расположения руля'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robotic', 'Робот'), ('cvt', 'Вариатор')], max_length=300, null=True, verbose_name='Тип КПП'),
        ),
        migrations.AddField(
            model_name='carsposts',
            name='video_url',
            field=models.URLField(default=1, verbose_name='URL to video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='carsposts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
