# Generated by Django 5.1.1 on 2024-09-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0002_carsposts_availability_carsposts_car_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carsposts',
            options={'verbose_name': 'Car post', 'verbose_name_plural': 'Cars posts'},
        ),
        migrations.AlterField(
            model_name='carsposts',
            name='other',
            field=models.CharField(choices=[('recently_delivered', 'Свежепригнан'), ('tax_paid', 'Налог уплачен'), ('inspection_passed', 'Технический осмотр пройден'), ('no_investment_required', 'Вложений не требуются')], max_length=300, null=True, verbose_name='Прочее'),
        ),
    ]
