# Generated by Django 5.1.1 on 2024-09-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0004_exterior_generaloptions_interior_media_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsposts',
            name='exterior',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='cars_posts.exterior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='interior',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='cars_posts.interior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='media',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='cars_posts.media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='options',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='cars_posts.generaloptions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsposts',
            name='security',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='cars_posts.security'),
            preserve_default=False,
        ),
    ]
