# Generated by Django 5.1.1 on 2024-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0005_carsposts_exterior_carsposts_interior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsposts',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар'), ('SOM', 'СОМ')], max_length=300, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='carsposts',
            name='exchange_possibility',
            field=models.CharField(choices=[('will_consider_options', 'Рассмотрю варианты'), ('extra_charge_buyer', 'С доплатой от покупателя'), ('extra_charge_seller', 'С доплатой от продавца'), ('no_additional_payments', 'Обмен без доплат'), ('not_interested', 'Не интересует обмен'), ('real_estate_exchange', 'Обмен на недвижимость'), ('only_exchange', 'Только обмен')], max_length=30, null=True, verbose_name='Возможность обмена'),
        ),
        migrations.AlterField(
            model_name='carsposts',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='carsposts',
            name='video_url',
            field=models.URLField(verbose_name='URL для видео'),
        ),
    ]
