# Generated by Django 5.1.1 on 2024-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_posts', '0006_alter_carsposts_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsposts',
            name='video_url',
            field=models.URLField(null=True, verbose_name='URL для видео'),
        ),
    ]
